### ISSUE TITLE
Processing status doc

### ISSUE THREAD

**Issue by pgbrodrick** [EvanDLang/SHIFT-SMCE-User-Guide#8]
Hey Evan,

Can you add a reference to this sheet: https://docs.google.com/spreadsheets/d/1nRZrnOmFYnMBVycDP-03j4_eQ-WxJIsvEXe62Yu65LI/edit#gid=0 onto S3 somewhere?  Some folks have requested being able to read these in for different processing.

**Comment by EvanDLang** [comment]
Hey Phil,

Would you be able to give me access to the doc?

Thanks!

**Comment by m11keluis** [comment]
Hey Evan, 

I copied the spreadsheet into the efs folder as a csv. I wasn't sure the best place for a shared file to live, so feel free to move it around. 

Thanks!
